In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
!pip freeze --local > /content/gdrive/My\ Drive/colab_installed.txt

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


**Important PIP instols**

In [ ]:
!pip3 install --upgrade Keras
import csv
import tensorflow as tf
import numpy as np
import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences



  Found existing installation: Keras 2.3.1
    Uninstalling Keras-2.3.1:
      Successfully uninstalled Keras-2.3.1


**Extracting texts from .text files and lableing** 

In [ ]:
import sklearn
from sklearn import datasets
from pprint import pprint 

random_state1=100

docs_to_train = sklearn.datasets.load_files("/content/gdrive/My Drive/Colab Notebooks/All_Data_1_2/Text_Data_7_Categories", description=None, categories=None,
                                            load_content=True, shuffle=True, 
                                            encoding='utf-8', decode_error='strict', random_state=random_state1)


#print(docs_to_train)
#print(list(docs_to_train.target_names))

#print(list(docs_to_train.data))

# print(docs_to_train)

# for i in range(1):
#   print(docs_to_train.data[i], docs_to_train.target[i])

# print(docs_to_train.data)
# print(docs_to_train.target)
print(docs_to_train.target_names)

c = dict(docs_to_train)



sentences=c['data']
label=c['target']
labels=np.array(label)
print(labels)
print(len(labels))




['1_Label_Documents_Text', '2_Clinical_Study Protocol_Documents_Text', '5_Pharmacological_Review_Documents_Text', '6_Articles_Text', '7_Medical_Review_Documents_Text', '8_Microbiology_Review_Documents_Text', '9. Clinical Pharmacology _ Biopharmaceutics Review Documents_Text']
[2 4 3 ... 5 5 3]
1009


**Import Pikles**

In [ ]:
import pickle
# loading start here

with open('/content/gdrive/My Drive/Colab Notebooks/Final_Codes/Save_Tokenisers/tokenizer_first_n_words.pickle', 'rb') as handle:

    tokenizer_n = pickle.load(handle)

import pickle
with open('/content/gdrive/My Drive/Colab Notebooks/Final_Codes/Save_Tokenisers/tokenizer_for_test.pickle', 'rb') as hand:

    tokenizer1 = pickle.load(hand)

**Hyperparameters**

In [ ]:

test_portion = .7
remove=75


**Split data into train_validation (train data validation data) and test data**

In [ ]:
train_and_cross_val_Test_size = int(len(sentences) * (1-test_portion))

train_cross_val = sentences[:train_and_cross_val_Test_size]
train_labels_cross_val = labels[:train_and_cross_val_Test_size]

control_test_sentences = sentences[train_and_cross_val_Test_size:]
control_test_labels = labels[train_and_cross_val_Test_size:]
print((control_test_labels))


print(len(train_cross_val))
print(len(train_labels_cross_val))
print(len(control_test_sentences))

[1 3 3 0 3 0 3 2 3 0 0 6 1 3 5 6 1 0 4 0 3 2 6 2 3 0 3 5 0 4 6 1 2 4 2 3 5
 0 2 6 4 6 4 3 2 4 4 5 2 2 4 5 0 3 3 2 6 5 6 3 5 2 0 5 2 2 3 3 4 4 3 4 3 4
 4 1 0 0 0 4 0 2 0 1 3 6 1 5 5 3 6 0 5 4 4 0 6 4 4 0 5 2 6 3 6 4 2 4 1 2 2
 2 5 3 2 0 2 1 2 6 6 6 6 0 5 3 3 4 5 5 2 6 5 3 3 2 6 2 0 5 4 6 5 6 6 5 3 0
 6 6 6 4 4 2 4 4 4 2 6 6 0 5 1 2 3 3 6 5 2 2 2 2 4 5 6 2 6 2 6 2 2 4 3 6 0
 3 6 2 4 2 2 2 3 6 5 4 3 3 6 3 0 3 5 0 0 2 5 6 2 2 1 5 1 5 6 2 5 4 5 2 2 6
 0 0 0 2 2 5 6 6 4 2 3 3 5 6 0 0 2 0 0 5 0 0 3 1 5 4 6 4 3 3 4 3 2 0 4 4 4
 2 6 3 2 6 0 6 5 2 6 2 3 0 1 6 3 0 3 0 5 3 6 2 6 3 6 6 6 4 0 4 4 6 5 2 6 5
 2 0 3 5 5 4 6 0 3 2 0 1 4 6 0 3 4 3 4 5 4 4 2 2 4 2 0 2 2 0 0 2 2 2 5 3 1
 5 4 0 4 6 3 4 6 1 5 6 2 6 1 4 1 4 2 5 3 6 2 5 5 5 3 1 4 5 4 6 2 5 5 0 5 3
 4 3 3 3 2 5 6 4 0 3 4 2 4 2 5 5 4 3 4 4 0 4 0 4 2 2 0 1 5 6 4 2 4 5 6 0 5
 6 2 2 4 0 1 6 6 5 2 5 6 3 2 2 3 6 2 6 0 3 6 0 0 6 2 2 4 5 5 4 6 5 4 0 6 2
 0 6 4 4 5 2 0 3 3 2 2 0 5 4 5 5 4 2 6 0 1 1 0 6 2 6 4 6 3 5 4 0 2 6 4 0 6
 2 6 1 4 4 2 0 4 5 6 0 5 

**Getting unwanted words from our obtained vocabulary**

In [ ]:
first_n_words1=[]

for i in range(remove):
  first_n_words1.append(tokenizer_n.index_word[i+1])

print(first_n_words1)

unwanted_words = first_n_words1
#print(len(stopwords))
print(unwanted_words)
print(len(unwanted_words))

['<OOV>', 'the', 'of', 'and', 'in', 'to', 'a', 'for', '1', '0', '2', 'with', '3', 'is', 'was', 'or', 'be', 'study', '5', 'were', '4', 'mg', 'on', 'at', 'patients', 'that', 'as', '6', 'by', 'dose', 'this', 'from', 'not', 'treatment', 'are', '7', '8', 'pageul', '10', 'will', 'drug', 'no', 'an', '12', 'clinical', 'day', 'e', '9', '20', 'kg', 'studies', 'data', 'n', 'have', 'nda', 's', 'use', 'subjects', 'ml', 'table', 'may', '—', 'after', 'these', 'all', 'group', 'been', 'review', 'd', 'other', 'than', '15', 'should', '11', 'al']
['<OOV>', 'the', 'of', 'and', 'in', 'to', 'a', 'for', '1', '0', '2', 'with', '3', 'is', 'was', 'or', 'be', 'study', '5', 'were', '4', 'mg', 'on', 'at', 'patients', 'that', 'as', '6', 'by', 'dose', 'this', 'from', 'not', 'treatment', 'are', '7', '8', 'pageul', '10', 'will', 'drug', 'no', 'an', '12', 'clinical', 'day', 'e', '9', '20', 'kg', 'studies', 'data', 'n', 'have', 'nda', 's', 'use', 'subjects', 'ml', 'table', 'may', '—', 'after', 'these', 'all', 'group', 'b

**General stop words**

In [ ]:
stopwords = [ "a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are", "as", "at", "be", "because", 
             "been", "before", "being", "below", "between", "both", "but", "by", "could", "did", "do", "does", "doing", "down", "during", 
             "each", "few", "for", "from", "further", "had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here", 
             "here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", 
             "is", "it", "it's", "its", "itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on", "once", "only", "or", 
             "other", "ought", "our", "ours", "ourselves", "out", "over", "own", "same", "she", "she'd", "she'll", "she's", "should", "so", 
             "some", "such", "than", "that", "that's", "the", "their", "theirs", "them", "themselves", "then", "there", "there's", "these", 
             "they", "they'd", "they'll", "they're", "they've", "this", "those", "through", "to", "too", "under", "until", "up", "very", 
             "was", "we", "we'd", "we'll", "we're", "we've", "were", "what", "what's", "when", "when's", "where", "where's", "which", 
             "while", "who", "who's", "whom", "why", "why's", "with", "would", "you", "you'd", "you'll", "you're", "you've", "your", 
             "yours", "yourself", "yourselves" ]
stopwords=[]
print(len(stopwords))

0


**Combined unwanted words**

In [ ]:
unwanted_words = stopwords+first_n_words
print(len(stopwords))
print(unwanted_words)
print(len(unwanted_words))

0
['<OOV>', 'the', 'of', 'and', 'in', 'to', 'a', 'for', '1', '0', '2', 'with', '3', 'is', 'was', 'or', 'be', 'study', '5', 'were', '4', 'mg', 'on', 'at', 'patients', 'that', 'as', '6', 'by', 'dose', 'this', 'from', 'not', 'treatment', 'are', '7', '8', 'pageul', '10', 'will', 'drug', 'no', 'an', '12', 'clinical', 'day', 'e', '9', '20', 'kg', 'studies', 'data', 'n', 'have', 'nda', 's', 'use', 'subjects', 'ml', 'table', 'may', '—', 'after', 'these', 'all', 'group', 'been', 'review', 'd', 'other', 'than', '15', 'should', '11', 'al']
75


**Function wich remoove words from list of words**

In [ ]:
def remove_words(words):
    """Remove words from list of words"""
    new_words = []
    for word in words:
        if word not in unwanted_words:
            new_words.append(word)
    return new_words

**Function wich filter sentences**

In [ ]:
def filtered(sentenc):
  filtered_sentences = []
  for sent in sentenc:
   lis = tf.keras.preprocessing.text.text_to_word_sequence(sent, filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n', lower=True, split=' ')
   lis = remove_words(lis)
   filtered_sentence = (" ").join(lis)
   filtered_sentences.append(filtered_sentence)
  return filtered_sentences


**Continuing data preprocessing (padding of filtered sentences)**

In [ ]:
control_test_sentences_fil=filtered(control_test_sentences )

control_test_sentences_seq = tokenizer1.texts_to_sequences(control_test_sentences_fil)

control_test_sentences_padded= pad_sequences(control_test_sentences_seq , padding=padding_type, maxlen=max_length)
control_test_labels_seq=np.expand_dims(control_test_labels,axis=1)

#print(control_test_sentences_seq[32] )

**Load Models**

In [ ]:
# Recreate the exact same model purely from the file

new_model1=tf.keras.models.load_model('/content/gdrive/My Drive/Colab Notebooks/Final_Codes/Save_Models/my_model_fold1.h5')
new_model2=tf.keras.models.load_model('/content/gdrive/My Drive/Colab Notebooks/Final_Codes/Save_Models/my_model_fold2.h5')
new_model3=tf.keras.models.load_model('/content/gdrive/My Drive/Colab Notebooks/Final_Codes/Save_Models/my_model_fold3.h5')
new_model4=tf.keras.models.load_model('/content/gdrive/My Drive/Colab Notebooks/Final_Codes/Save_Models/my_model_fold4.h5')
new_model5=tf.keras.models.load_model('/content/gdrive/My Drive/Colab Notebooks/Final_Codes/Save_Models/my_model_fold5.h5')
  


In [ ]:
print(new_model1.evaluate(control_test_sentences_padded,control_test_labels_seq, batch_size=32))
print()
print(new_model2.evaluate(control_test_sentences_padded,control_test_labels_seq, batch_size=32))
print()
print(new_model3.evaluate(control_test_sentences_padded,control_test_labels_seq, batch_size=32))
print()
print(new_model4.evaluate(control_test_sentences_padded,control_test_labels_seq, batch_size=32))
print()
print(new_model5.evaluate(control_test_sentences_padded,control_test_labels_seq, batch_size=32))

23/23 [==============================] - 0s 6ms/step - loss: 0.8740 - accuracy: 0.9802
[0.8739928603172302, 0.9801980257034302]

23/23 [==============================] - 0s 6ms/step - loss: 0.6035 - accuracy: 0.9830
[0.6034698486328125, 0.9830268621444702]

23/23 [==============================] - 0s 6ms/step - loss: 0.5158 - accuracy: 0.9774
[0.515779435634613, 0.9773691892623901]

23/23 [==============================] - 0s 6ms/step - loss: 0.8647 - accuracy: 0.9844
[0.864692747592926, 0.9844412803649902]

23/23 [==============================] - 0s 6ms/step - loss: 0.6917 - accuracy: 0.9745
[0.691733717918396, 0.9745402932167053]


**Confusion Matrix for Model1**

In [ ]:
y_pred=new_model1.predict_classes(control_test_sentences_padded)


con_mat = tf.math.confusion_matrix(labels=control_test_labels_seq, predictions=y_pred).numpy()

print(con_mat)

print()

print((control_test_labels))
print(y_pred)                                      #aij-should be i, but model predicts j (i,j=0;1...)



[[78  0  0  0  0  0  1]
 [ 1 27  1  1  1  0  0]
 [ 0  0 84  0  1  0  0]
 [ 0  0  0 68  0  0  0]
 [ 1  0  4  0 74  0  0]
 [ 0  0  0  0  2 85  0]
 [ 0  0  0  0  0  0 76]]

[5 0 0 2 5 6 2 2 1 5 1 5 6 2 5 4 5 2 2 6 0 0 0 2 2 5 6 6 4 2 3 3 5 6 0 0 2
 0 0 5 0 0 3 1 5 4 6 4 3 3 4 3 2 0 4 4 4 2 6 3 2 6 0 6 5 2 6 2 3 0 1 6 3 0
 3 0 5 3 6 2 6 3 6 6 6 4 0 4 4 6 5 2 6 5 2 0 3 5 5 4 6 0 3 2 0 1 4 6 0 3 4
 3 4 5 4 4 2 2 4 2 0 2 2 0 0 2 2 2 5 3 1 5 4 0 4 6 3 4 6 1 5 6 2 6 1 4 1 4
 2 5 3 6 2 5 5 5 3 1 4 5 4 6 2 5 5 0 5 3 4 3 3 3 2 5 6 4 0 3 4 2 4 2 5 5 4
 3 4 4 0 4 0 4 2 2 0 1 5 6 4 2 4 5 6 0 5 6 2 2 4 0 1 6 6 5 2 5 6 3 2 2 3 6
 2 6 0 3 6 0 0 6 2 2 4 5 5 4 6 5 4 0 6 2 0 6 4 4 5 2 0 3 3 2 2 0 5 4 5 5 4
 2 6 0 1 1 0 6 2 6 4 6 3 5 4 0 2 6 4 0 6 2 6 1 4 4 2 0 4 5 6 0 5 5 2 5 2 0
 6 0 4 3 6 4 5 5 3 3 3 1 0 2 0 2 6 0 5 3 0 2 3 2 4 4 5 4 5 2 0 2 4 4 2 4 3
 5 3 5 0 5 1 1 0 4 3 3 0 5 3 0 3 5 6 3 2 6 2 5 5 4 2 1 4 0 4 2 3 3 5 3 3 5
 3 3 3 5 3 1 5 1 6 5 2 3 0 2 5 0 4 5 4 0 5 1 6 0 1 0 5 5 0 5 1 1 6 6 3 3 1
 2 5 

**Confusion Matrix for Model2**

In [ ]:
y_pred=new_model2.predict_classes(control_test_sentences_padded)


con_mat = tf.math.confusion_matrix(labels=control_test_labels_seq, predictions=y_pred).numpy()

print(con_mat)

print()

print((control_test_labels))
print(y_pred)                                       #aij-should be i, but model predicts j (i,j=0;1...)

[[26  0  0  0  0  0  1]
 [ 0 10  1  3  1  0  0]
 [ 0  0 21  0  1  0  0]
 [ 0  0  0 29  0  0  0]
 [ 0  0  1  0 19  1  0]
 [ 0  0  0  0  0 34  0]
 [ 0  0  1  0  0  0 23]]

[5 3 5 0 5 1 1 0 4 3 3 0 5 3 0 3 5 6 3 2 6 2 5 5 4 2 1 4 0 4 2 3 3 5 3 3 5
 3 3 3 5 3 1 5 1 6 5 2 3 0 2 5 0 4 5 4 0 5 1 6 0 1 0 5 5 0 5 1 1 6 6 3 3 1
 2 5 1 4 4 0 2 3 1 0 0 5 4 3 2 3 0 6 0 0 4 3 4 2 5 3 6 1 2 1 5 6 4 2 6 6 2
 2 5 2 1 0 3 3 4 6 0 2 5 4 5 2 5 3 0 0 6 6 4 0 4 5 5 0 6 3 6 6 4 2 0 0 4 3
 6 4 2 6 2 4 2 5 5 3 5 4 0 6 6 2 6 6 0 5 6 5 5 3]
[5 3 5 0 5 4 1 0 4 3 3 0 5 3 0 3 5 6 3 2 6 2 5 5 4 2 3 4 0 4 2 3 3 5 3 3 5
 3 3 3 5 3 1 5 2 6 5 4 3 0 2 5 0 4 5 4 0 5 1 6 0 1 0 5 5 0 5 1 3 6 6 3 3 3
 2 5 1 4 4 0 2 3 1 0 0 5 4 3 2 3 6 6 0 0 4 3 4 2 5 3 6 1 2 1 5 6 4 2 6 6 2
 2 5 2 1 0 3 3 2 6 0 2 5 4 5 2 5 3 0 0 6 6 5 0 4 5 5 0 6 3 6 6 4 2 0 0 4 3
 6 4 2 6 2 4 2 5 5 3 5 4 0 6 6 2 6 2 0 5 6 5 5 3]


**Confusion Matrix for Model3**

In [ ]:
y_pred=new_model3.predict_classes(control_test_sentences_padded)


con_mat = tf.math.confusion_matrix(labels=control_test_labels_seq, predictions=y_pred).numpy()

print(con_mat)

print()

print((control_test_labels))
print(y_pred)                             #aij-should be i, but model predicts j (i,j=0;1...)

[[26  0  0  0  0  0  1]
 [ 1 10  1  3  0  0  0]
 [ 0  0 21  0  1  0  0]
 [ 0  0  1 28  0  0  0]
 [ 0  0  2  0 19  0  0]
 [ 0  0  1  0  0 33  0]
 [ 0  0  1  0  0  0 23]]

[5 3 5 0 5 1 1 0 4 3 3 0 5 3 0 3 5 6 3 2 6 2 5 5 4 2 1 4 0 4 2 3 3 5 3 3 5
 3 3 3 5 3 1 5 1 6 5 2 3 0 2 5 0 4 5 4 0 5 1 6 0 1 0 5 5 0 5 1 1 6 6 3 3 1
 2 5 1 4 4 0 2 3 1 0 0 5 4 3 2 3 0 6 0 0 4 3 4 2 5 3 6 1 2 1 5 6 4 2 6 6 2
 2 5 2 1 0 3 3 4 6 0 2 5 4 5 2 5 3 0 0 6 6 4 0 4 5 5 0 6 3 6 6 4 2 0 0 4 3
 6 4 2 6 2 4 2 5 5 3 5 4 0 6 6 2 6 6 0 5 6 5 5 3]
[5 3 5 0 5 0 1 0 4 3 3 0 5 3 0 3 5 6 3 2 6 2 5 5 4 2 3 4 0 4 2 3 3 5 3 3 5
 3 3 3 5 3 1 5 2 6 5 4 3 0 2 5 0 4 5 4 0 5 1 6 0 1 0 5 5 0 2 1 3 6 6 3 3 3
 2 5 1 4 4 0 2 3 1 0 0 5 4 3 2 3 6 6 0 0 2 3 4 2 5 3 6 1 2 1 5 6 4 2 6 6 2
 2 5 2 1 0 3 2 2 6 0 2 5 4 5 2 5 3 0 0 6 6 4 0 4 5 5 0 6 3 6 6 4 2 0 0 4 3
 6 4 2 6 2 4 2 5 5 3 5 4 0 6 6 2 6 2 0 5 6 5 5 3]


**Confusion Matrix for Model4**

In [ ]:
y_pred=new_model4.predict_classes(control_test_sentences_padded)


con_mat = tf.math.confusion_matrix(labels=control_test_labels_seq, predictions=y_pred).numpy()

print(con_mat)

print()

print((control_test_labels))
print(y_pred)                    #aij-should be i, but model predicts j (i,j=0;1...)

[[26  0  0  0  0  0  1]
 [ 1 11  1  2  0  0  0]
 [ 0  0 21  0  1  0  0]
 [ 0  0  0 29  0  0  0]
 [ 0  0  1  0 19  1  0]
 [ 0  0  0  0  0 34  0]
 [ 0  0  0  0  0  0 24]]

[5 3 5 0 5 1 1 0 4 3 3 0 5 3 0 3 5 6 3 2 6 2 5 5 4 2 1 4 0 4 2 3 3 5 3 3 5
 3 3 3 5 3 1 5 1 6 5 2 3 0 2 5 0 4 5 4 0 5 1 6 0 1 0 5 5 0 5 1 1 6 6 3 3 1
 2 5 1 4 4 0 2 3 1 0 0 5 4 3 2 3 0 6 0 0 4 3 4 2 5 3 6 1 2 1 5 6 4 2 6 6 2
 2 5 2 1 0 3 3 4 6 0 2 5 4 5 2 5 3 0 0 6 6 4 0 4 5 5 0 6 3 6 6 4 2 0 0 4 3
 6 4 2 6 2 4 2 5 5 3 5 4 0 6 6 2 6 6 0 5 6 5 5 3]
[5 3 5 0 5 0 1 0 4 3 3 0 5 3 0 3 5 6 3 2 6 2 5 5 4 2 3 4 0 4 2 3 3 5 3 3 5
 3 3 3 5 3 1 5 2 6 5 4 3 0 2 5 0 4 5 4 0 5 1 6 0 1 0 5 5 0 5 1 3 6 6 3 3 1
 2 5 1 4 4 0 2 3 1 0 0 5 4 3 2 3 6 6 0 0 2 3 4 2 5 3 6 1 2 1 5 6 4 2 6 6 2
 2 5 2 1 0 3 3 4 6 0 2 5 4 5 2 5 3 0 0 6 6 4 0 4 5 5 0 6 3 6 6 5 2 0 0 4 3
 6 4 2 6 2 4 2 5 5 3 5 4 0 6 6 2 6 6 0 5 6 5 5 3]


**Confusion Matrix for Model5**

In [ ]:
y_pred=new_model5.predict_classes(control_test_sentences_padded)


con_mat = tf.math.confusion_matrix(labels=control_test_labels_seq, predictions=y_pred).numpy()

print(con_mat)

print()

print((control_test_labels))
print(y_pred)                          #aij-should be i, but model predicts j (i,j=0;1...)

[[25  0  0  0  1  0  1]
 [ 1 10  1  3  0  0  0]
 [ 0  0 21  0  1  0  0]
 [ 0  0  0 29  0  0  0]
 [ 0  0  2  0 19  0  0]
 [ 0  0  0  0  1 33  0]
 [ 0  0  0  0  0  0 24]]

[5 3 5 0 5 1 1 0 4 3 3 0 5 3 0 3 5 6 3 2 6 2 5 5 4 2 1 4 0 4 2 3 3 5 3 3 5
 3 3 3 5 3 1 5 1 6 5 2 3 0 2 5 0 4 5 4 0 5 1 6 0 1 0 5 5 0 5 1 1 6 6 3 3 1
 2 5 1 4 4 0 2 3 1 0 0 5 4 3 2 3 0 6 0 0 4 3 4 2 5 3 6 1 2 1 5 6 4 2 6 6 2
 2 5 2 1 0 3 3 4 6 0 2 5 4 5 2 5 3 0 0 6 6 4 0 4 5 5 0 6 3 6 6 4 2 0 0 4 3
 6 4 2 6 2 4 2 5 5 3 5 4 0 6 6 2 6 6 0 5 6 5 5 3]
[5 3 5 0 4 0 1 0 4 3 3 0 5 3 0 3 5 6 3 2 6 2 5 5 4 2 3 4 0 4 2 3 3 5 3 3 5
 3 3 3 5 3 1 5 2 6 5 4 3 0 2 5 0 4 5 4 0 5 1 6 0 1 0 5 5 0 5 1 3 6 6 3 3 3
 2 5 1 4 4 0 2 3 1 0 0 5 4 3 2 3 6 6 0 0 2 3 4 2 5 3 6 1 2 1 5 6 4 2 6 6 2
 2 5 2 1 0 3 3 2 6 0 2 5 4 5 2 5 3 0 0 6 6 4 0 4 5 5 0 6 3 6 6 4 2 4 0 4 3
 6 4 2 6 2 4 2 5 5 3 5 4 0 6 6 2 6 6 0 5 6 5 5 3]
